name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show workspace tree (debug)
        run: |
          pwd
          echo "---- ROOT LIST ----"
          ls -la
          echo "---- settings.gradle ----"
          sed -n '1,200p' settings.gradle || true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # رفع مشکل CRLF برای gradlew (اگر کسی با ویندوز کامیت کرد)
      - name: Normalize EOL for gradlew (fix CRLF)
        run: sed -i 's/\r$//' gradlew

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: QuickShare-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: QuickShare-release-apk
          path: app/build/outputs/apk/release/app-release.apk


